language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn lint
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-template
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-template
    skip-cleanup: true
    script: yarn deploy:prod
    on:
      branch: prod
