language: node_js
node_js:
- '12'
env:
  global:
  - DEPLOY_REPOSITORY="git@github.com:konnectors/ensap.git"
  # REGISTRY_TOKEN(editor=cozy, app=ecoledirecte)
  - secure: Dx9eQ2al6ni+DhxsGd230QHi/Du+szUsJAeZcvFyRnkxQJ/voXVbstjF4UHuQpvtPr55rpE7c4w2Ur3XHM6nlKIAWWww+wvmxa9BsBk7oSE86lcs5297xOThSNHw2xiei2O8cCZQ3iOrLB+zt+veegOXp/3WZcK8U9awZUhnsRdyMuTOFsIqj3jarS8jnqr1OSp7OeEvWk2ivygWCKuEtlx19H6BaQ2L1CdIp3YSnIkrjxkUIIYnrLnobHemXWCXBYdBlJ9wTQcAFZjxB0a7UnFM+OBKhXcdBHkirmWcHTKk8tMiFJGyJLYbmIyzaU1JJcftt8Ki6Hd1aIDyzCW7PqgMTq77WSig1Q2SxsYkIq8yz5a9+JCCkVaiR14AIeCBZPch2EKX7BYtrzUdB+YdI0fl0DQ+thc4Moljbuagb9HGAIj7tW86ssSmGhHUy0tIT26yfx02/diaVPgsPYglald4q2lCRrpjnOjZZGFxhI8hRnIuUSBDegkYs2i+vrQTXCljEp1Qi5CVm5na40NhRTyXhzaOjSsJ/1m3hpcb+SYmEfZQYhnH21EoOuQI9EmvQcBPxFRM2IYrF+aBZytTS1//Z2SONGOAinh3ADIzPksqT9KzKFXNJ4yblrkPWGRcQroZ20rI4XmRlrZv03HL9c+YesBk51zPA8niBKZ9cIE=
  # MATTERMOST_HOOK_URL
  - secure: pofrkNm39uST5w3TylI6SEoj+0awkWNWz0pamAbAPvbuxpnb/Tin/YUT5piFpAkNp/sRf5TeCr6T2p9AEA3RpS1lfbdS9KTlYt7/gobQO0qbnY+xo2fFBEIA31Fq8E3LWcFGEQDYabY3Q3KHKDROWzUPcI+qybEWGB6guBZZKX/9YcphKDKHs7P6MWwWlBhf9v6vJ7L3NYEU7sr+0vKfD8BIEihK4egB/LloyXNACvJ+Zm2nISCQY1Bnq2510dErb5ahsoEEaqV8/Ua0FXdCi6Cj1TUBX7a98bM2L3V02RB6/lEkGnXmkUIaxjAVnkIDVyqg83Kr4eoDKhhHAPPXXvMwXODNEGkLvZvyBFOIogGHYqT3x2StrZeiRvkz00z43ex+aDJxCtd8OkbfwYufwUDWMDqMOYGZ6wqQRjx344C7Y/ZQgG48VLMpnMUKlatdwpc+phdFaBXZPVfUY+HHiTQWVyzSm3K/S8tZggK6t0FD8lzu7woNioxSpnTVDmdLS1utbkLpNXknQbKa4+QuWmDD4ZgtHOMIUhluG86f8FQWJXy2YU0b6ZD3G7T4TxD7XVTDm2AtOCcJQ6JqEjrEJwPxQHpwCVPJCK2xIfBoXMInob8vjWjvYTzcHhvZiyuP98qLUGDzGuoasUVzclGonGfd2BYLHRvj3EW4s2+HzW4=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_b83be51a0af4_key -iv $encrypted_b83be51a0af4_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
